### ISSUE TITLE
Porn Sites to Add to Blacklist

### ISSUE THREAD

**Issue by allieraej** [net-angel/netangel-blacklists#4]
Fuq.com
Xhamster.com
Xhamstercams.com
Chaturbate.com
Pornhub.com (user says it was blocked the first time, but was able to get through after refreshing)
Jugworld.com
Realitykings.com

Customer: Deus Vult - herringtonmichael5@gmail.com 

@eterry1388

**Comment by eterry1388** [comment]
All of these are in the blacklist.  Three of them had httpS versions of the site.  I added those three to our DNS blacklist (so they will appear as if they are not on the internet at all).

Added these to DNS blacklist:
- xhamster.com
- Xhamstercams.com
- Chaturbate.com
